{
 "title": "Кро",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Количество предсказаний выше среднего",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yandex_app_morethanmedian_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Доля обработанных запросов",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "yandex_app_predictions_count",
     "legendFormat": "Запросов, получивших предсказания"
    },
    {
     "expr": "sum by(handler) (http_requests_total{handler=\"/predict/{user_id}\"})",
     "legendFormat": "Всего запросов"
    }
   ]
  },
  {
   "title": "Количество предсказаний в группе",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "yandex_app_predictions_bucket{le=\"8.6e+06\"}",
     "legendFormat": "<=8600000"
    },
    {
     "expr": "yandex_app_predictions_bucket{le=\"1.1e+07\"}",
     "legendFormat": "<=11000000"
    },
    {
     "expr": "yandex_app_predictions_bucket{le=\"1.445e+07\"}",
     "legendFormat": "<=14450000"
    },
    {
     "expr": "yandex_app_predictions_bucket{le=\"1.6e+07\"}",
     "legendFormat": "<=16000000"
    }
   ]
  },
  {
   "title": "Средняя цена",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "yandex_app_predictions_sum/yandex_app_predictions_count",
     "legendFormat": "среднее предсказание"
    }
   ]
  }
 ]
}