FROM python:3.11-slim

LABEL author=${AUTHOR}

COPY . ./services
WORKDIR services
RUN pip3 install -r requirements.txt
VOLUME /models

EXPOSE ${APP_PORT}

CMD uvicorn ml_service.main:app --host  0.0.0.0 --port ${APP_PORT}